COMMENT

   **************************************************
   File generated by: neuroConstruct v1.6.0 
   **************************************************

   This file holds the implementation in NEURON of the Cell Mechanism:
   gapCond (Type: Gap junction, Model: File Based Membrane Mechanism)

   with parameters: 

ENDCOMMENT

COMMENT

   **************************************************
   File generated by: neuroConstruct v1.6.0 
   **************************************************

   This file holds the implementation in NEURON of the Cell Mechanism:
   gapCond (Type: Gap junction, Model: File Based Membrane Mechanism)

   with parameters: 

ENDCOMMENT

COMMENT

   **************************************************
   File generated by: neuroConstruct v1.5.3 
   **************************************************

   This file holds the implementation in NEURON of the Cell Mechanism:
   GJ (Type: Gap junction, Model: File Based Membrane Mechanism)

   with parameters: 

ENDCOMMENT

COMMENT

   **************************************************
   File generated by: neuroConstruct v1.5.0 
   **************************************************


ENDCOMMENT


?  This is a NEURON mod file generated from a ChannelML file

?  Unit system of original ChannelML file: Physiological Units

COMMENT
    ChannelML file describing a single synaptic mechanism
ENDCOMMENT

? Creating synaptic mechanism for an electrical synapse
    

TITLE Channel: GapJuncCML

COMMENT
    Description of an electrical synapse at a gap junction
ENDCOMMENT


UNITS {
    (nA) = (nanoamp)
    (mV) = (millivolt)
    (uS) = (microsiemens)
}

    
NEURON {
    POINT_PROCESS gapCond
    NONSPECIFIC_CURRENT i
    RANGE g, i
    RANGE weight
    
    POINTER vgap  : Using a POINTER as opposed to RANGE for serial mode
        

}

PARAMETER {
    v (millivolt)
    vgap (millivolt)
    g = 1e-6 (microsiemens)
    weight = 1

}


ASSIGNED {
    i (nanoamp)
}

BREAKPOINT {
    i = weight * g * (v - vgap)
} 
